service: lambda-with-typescript

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: line.hello
    events:
      - http:
          path: hello
          method: get

  lineWebhook:
    handler: line.webhook
    events:
      - http:
          path: line/webhook
          method: post
